# Generated by Django 3.1.1 on 2020-09-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salario',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
