# Generated by Django 3.1.1 on 2020-09-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('gender', models.CharField(max_length=8)),
                ('full_time', models.BooleanField()),
                ('birthday', models.DateField()),
            ],
        ),
    ]
