# Generated by Django 3.1.1 on 2020-10-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_employee_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salario',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
